name: Quality

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  quality:
    strategy:
      matrix:
        node-version: [ 12.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run lint
      - run: npm run test
